import type {Metadata} from "next";
import localFont from "next/font/local";
import "./globals.css";
import {SignedIn, SignedOut, SignInButton} from "@clerk/nextjs";
import Providers from "./providers";
import {Button} from "@/components/ui/button";
const jetbrainsMono = localFont({
  src: "./fonts/JetBrainsMono-ExtraBold.ttf",
  variable: "--font-jetbrains-mono",
  weight: "100 900",
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  "use client";
  return (
    <Providers>
      <html lang="en">
        <body className={`${jetbrainsMono.variable} ${jetbrainsMono.variable} antialiased w-full h-full`}>
          <SignedOut>
            <div className="flex flex-col justify-center items-center h-screen space-y-4">
              <h1 className="text-4xl font-bold">MARKET MADNESS</h1>
              <Button variant="outline" className="h-8 px-2 text-sm">
                <SignInButton signUpForceRedirectUrl={process.env.NEXT_PUBLIC_CLERK_SIGN_UP_FALLBACK_REDIRECT_URL} />
              </Button>
            </div>
          </SignedOut>
          <SignedIn>{children}</SignedIn>
        </body>
      </html>
    </Providers>
  );
}
